language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

script:
  - phpunit --coverage-text --coverage-clover=coverage.clover

after_script:
  - php vendor/bin/ocular code-coverage:upload --format=php-clover coverage.clover

before_script:
  - sudo apt-get update -q
  - sudo apt-get install -y imagemagick
  - wget http://getcomposer.org/composer.phar
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-source --dev
  - cp phpunit.xml.dist phpunit.xml